import { motion } from 'framer-motion';
import { X, Sparkles } from 'lucide-react';
import { TagRecord } from '../api';
import { cn } from '@/lib/utils';

interface TagProps {
  tag: TagRecord;
  onRemove?: () => void;
  onClick?: (e: React.MouseEvent) => void;
  isSelected?: boolean;
  size?: 'small' | 'medium';
}

export default function Tag({ tag, onRemove, onClick, isSelected = false, size = 'small' }: TagProps) {
  return (
    <motion.span
      initial={{ opacity: 0, scale: 0.9 }}
      animate={{ opacity: 1, scale: 1 }}
      exit={{ opacity: 0, scale: 0.9 }}
      whileHover={onClick ? { scale: 1.05 } : {}}
      className={cn(
        'inline-flex items-center gap-1.5 px-2 py-1 rounded-full font-medium border-2 transition-all',
        size === 'small' ? 'text-xs' : 'text-sm',
        onClick && 'cursor-pointer hover:brightness-110',
        isSelected && 'ring-2 ring-offset-2 ring-offset-black'
      )}
      style={{ 
        backgroundColor: isSelected ? `${tag.color}40` : `${tag.color}20`,
        borderColor: isSelected ? tag.color : `${tag.color}80`,
        color: tag.color,
        ...(isSelected && { ringColor: tag.color })
      }}
      onClick={onClick}
    >
      <span>{tag.name}</span>
      {tag.auto_generated && (
        <span title="Auto-generated by AI">
          <Sparkles size={12} />
        </span>
      )}
      {onRemove && (
        <motion.button
          className="hover:bg-black/20 rounded-full p-0.5"
          onClick={(e) => {
            e.stopPropagation();
            onRemove();
          }}
          aria-label={`Remove ${tag.name} tag`}
          whileHover={{ scale: 1.2 }}
          whileTap={{ scale: 0.8 }}
        >
          <X size={12} />
        </motion.button>
      )}
    </motion.span>
  );
}
